vich_uploader:
    db_driver: orm

    mappings:
        people_images:
            uri_prefix: /uploads/images/people
            upload_destination: '%kernel.project_dir%/public/uploads/images/people'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        genre_images:
            uri_prefix: /uploads/images/genre
            upload_destination: '%kernel.project_dir%/public/uploads/images/genre'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        theme_images:
            uri_prefix: /uploads/images/theme
            upload_destination: '%kernel.project_dir%/public/uploads/images/theme'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        artist_songs:
            uri_prefix: /uploads/audio/song
            upload_destination: '%kernel.project_dir%/public/uploads/audio/song'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug'}

        user_avatars:
            uri_prefix: /uploads/images/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        article_images:
            uri_prefix: /uploads/images/articles
            upload_destination: '%kernel.project_dir%/public/uploads/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
